### ISSUE TITLE
Micromix number is gone from tab title

### ISSUE THREAD

**Issue by kazes** [kazes/micromix#113]
in the tag <title> the # is missing the micromix number

**Comment by romuleald** [comment]
tag or tab?

**Comment by kazes** [comment]
it's the same :D tag title writes in the browser tab

**Comment by romuleald** [comment]
Need more information

What should be the title for:
* The homepage
* The homepage on page 2 or more
* The others pages (about, contact, etc)
* A mix page
* When sound play

**Comment by kazes** [comment]
ok pushed on master
