### ISSUE TITLE
add sound effects to the player

### ISSUE THREAD

**Issue by kazes** [kazes/micromix#53]
- push button
- release button
- open deck door
- close deck door
- cassette in
- cassette out
- fast forward
- fast rewind
- tape stop  (mix ending)

**Comment by romuleald** [comment]
Done 1e5e8a3376a51ae0697a5b5a49eafb8cadf88f57

**Comment by romuleald** [comment]
NEED VALIDATION

**Comment by kazes** [comment]
ok pushed to master
